### ISSUE TITLE
Confuse

### ISSUE THREAD

**Issue by suyukun666** [FriedRonaldo/PsyNet#4]
Hi!  In your work, you proposed a self-supervised training mechanism. But in the code, I observed that both VGG and SEResNet use a network pretrained on ImageNet and then train your net. 
（1）As far as I know, some self-supervised training such as SimCLR and MoCo are not pretrained on Imagenet.
（2）In the direct use of the pretrained SEResNet last layer feature visualization results and your training comparison, the visualization results are not very different.
  (3) How helpful the results in the paper are from the pretrained network on ImageNet?

**Comment by FriedRonaldo** [comment]
Yes, as you observed, PsyNet utilizes a pre-trained model and this is described in the paper. It is because PsyNet is not a self-supervised learning method but takes a self-supervised approach for solving the co-localization problem. (1)

We also conduct the localization with a pre-trained network without post-training. However, it exhibits an inferior performance. Unfortunately, we lost the results.  (2)

The previous co-localization methods utilize ImageNet pre-trained networks to extract meaningful features as weakly-supervised OL methods (e.g. CAM, ACoL, and ADL).  (3)

Without the pre-trained networks, the methods including WSOL methods can not work well on the fine-grained dataset or co-localization dataset. Especially, DDT, SCDA, Mining object and PsyNet can not perform proper localization w/o pre-trained network. (3)

However, the ImageNet pre-trained network can be replaced with MoCo or BYOL pre-trained network to be meaningful.
