### ISSUE TITLE
About CAAM

### ISSUE THREAD

**Issue by balablb** [FriedRonaldo/PsyNet#5]
How do I get CAAM and use it in training?

**Comment by FriedRonaldo** [comment]
CAAM is not used in the training phase because it is a way to extract heatmap from a network for localization.
It is equivalent to CAM in weakly supervised OL. (CAM is not used for training.)

In the [validation](https://github.com/FriedRonaldo/PsyNet/blob/master/validation.py#L172), you can find how to get a heatmap by CAAM.
